import "/styles/globals.css";
import { Marcellus, Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";

const marcellus = Marcellus({
  subsets: ["latin"],
  weight: "400",

  variable: "--font-marcellus",
});

export const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],

  variable: "--font-inter",
});

export const metadata = {
  title: "Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${marcellus.variable}`}>
        {children}
      </body>
    </html>
  );
}
